apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.containerPort }}
      targetPort: http
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.metricsPort }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    components: {{ .Values.componentsLabel }}